frameworkcss: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css
frameworkcss_integrity: sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3
#frameworkcsstheme:
frameworkscript: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js
frameworkscript_integrity: sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13
popperscript: https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js
popperscript_integrity: sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB
mathscript: http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#jqueryscript: https://code.jquery.com/jquery-3.4.1.slim.min.js
css: /assets/themes/default/css/style.css
favicon: /assets/themes/default/img/favicon.ico
touch_icon: /assets/themes/default/img/apple-touch-icon-precomposed.png
header_image: /assets/themes/default/img/title.jpg
#header_pattern: "linear-gradient(to bottom,#563d7c 0,#6f5499 100%)"
header_text_color: "white"
header_style: fluid # fluid or fit
header_title_class: "header-title"
header_description_class: "header-description"
#footer: disable
#wallpaper_image: /assets/themes/default/img/wallpaper.jpg
#wallpaper_pattern: "linear-gradient(to bottom,#563d7c 0,#6f5499 100%)"
#content_text_color: "white"
#wallpaper_repeat: repeat
#navbar_brand_icon: glyphicon-home
navbar_brand_caption: "Site Title"
#navbar_brand_image: /assets/themes/default/img/apple-touch-icon-precomposed.png
#navbar_brand_image_alt: brand
#navbar_layout: top
navbar_style: navbar-expand-lg navbar-light bg-light
navbar_layout: top # top or middle or bottom or none
#navbar_style: navbar-default navbar-fixed-top navbar-inverse
navbar_search_box: true
sidearea_layout: left # right or left or both or none
table_style: table-striped
doc_navigator: bottom # top or bottom or both or none
doc_breadcrumb: enable
responsive_breakpoint: sm #sm md lg xl
#script_top: ! '
#'
#script_bottom: ! '
#'
